theme: jekyll-theme-minimal
title: MaxiPago SDK (.NET)
description: The MaxiPago SDK for .NET projects
logo: https://raw.githubusercontent.com/guibranco/MaxiPago-SDK-dotnet/master/logo.png
show_downloads: true
